name: blacktest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        # python-version: [3.9.5, 3.10.0]
        # python-version: [3.9.5]
        python-version: [3.9]
        # python-version: [3.10.0]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install flake8
    - name: Test with Black
      run: |
        # black --check cli --diff
        # black --check geo --diff
        black --check . --diff
    - name: Test with flake8
      run: |
        flake8 --ignore E203,E501,W503 . --statistics
